"""Read-only SSH collection primitives."""

from .ssh import (
    MAX_OUTPUT_BYTES,
    MAX_OUTPUT_LINES,
    MONITOR_CONNECTION_LIMIT,
    POLL_DEADLINE_SECONDS,
    CancellationToken,
    CollectorError,
    CollectorPhase,
    CommandBatch,
    CommandConnection,
    CommandOutput,
    HostKeyApproval,
    HostKeyInfo,
    MonitoringSSHConnectionFactory,
    PollDeadline,
    SSHCollector,
    SSHConnectionFactory,
    StrictNetmikoFactory,
    run_bounded_approval,
)

__all__ = [
    "MAX_OUTPUT_BYTES",
    "MAX_OUTPUT_LINES",
    "MONITOR_CONNECTION_LIMIT",
    "POLL_DEADLINE_SECONDS",
    "CancellationToken",
    "CollectorError",
    "CollectorPhase",
    "CommandBatch",
    "CommandConnection",
    "CommandOutput",
    "HostKeyApproval",
    "HostKeyInfo",
    "MonitoringSSHConnectionFactory",
    "PollDeadline",
    "SSHCollector",
    "SSHConnectionFactory",
    "StrictNetmikoFactory",
    "run_bounded_approval",
]
